/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'use_staff' at '17/07/14 14:59' with Gradle 2.14.1
 *
 * @author use_staff, @date 17/07/14 14:59
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
